INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Full Stack Developer', 'Globant', 'LinkedIn', 'www.url.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Frontend Developer', 'Google', 'Indeed', 'www.google.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Software Engineer', 'Microsoft', 'Glassdoor', 'www.microsoft.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Data Scientist', 'Facebook', 'LinkedIn', 'www.facebook.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('UX/UI Designer', 'Apple', 'Monster', 'www.apple.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Product Manager', 'Amazon', 'CareerBuilder', 'www.amazon.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Network Engineer', 'Cisco', 'SimplyHired', 'www.cisco.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Mobile App Developer', 'Samsung', 'Dice', 'www.samsung.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Database Administrator', 'Oracle', 'ZipRecruiter', 'www.oracle.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Cybersecurity Analyst', 'IBM', 'CareerJet', 'www.ibm.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('AI/Machine Learning Engineer', 'Tesla', 'TechCareers', 'www.tesla.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('DevOps Engineer', 'Netflix', 'LinkUp', 'www.netflix.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('IT Support Specialist', 'HP', 'JobsDB', 'www.hp.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Quality Assurance Tester', 'Intel', 'CareerOne', 'www.intel.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Business Analyst', 'Accenture', 'JobStreet', 'www.accenture.com', current_date, 'EN_PROCESO');
INSERT INTO postulaciones(puesto, empresa, plataforma, enlace, fecha, estado) VALUES('Cloud Solutions Architect', 'VMware', 'Recruit.net', 'www.vmware.com', current_date, 'EN_PROCESO');
